# Waterfall visualization constants.
FRAMERATE_HZ: float = 20.0

# Default user inputs.
DEFAULT_INPUT_CARRIER_FREQ_MHZ: float = 100.0
DEFAULT_INPUT_SAMPLING_FREQ_MHZ: float = 1.024
DEFAULT_INPUT_GAIN_DB: int = 0
DEFAULT_INPUT_RECV_BUFFER_SIZE: int = 50240
DEFAULT_INPUT_WATERFALL_DURATION_SEC: float = 10.0
DEFAULT_INPUT_WATERFALL_NFFT: int = 128
DEFAULT_FREQ_UNIT: str = "MHz"
